### PR TITLE
Ruby Demo app

### PR DESCRIPTION
**Pull request by rashidsp**

### CODE REVIEW

**Comment by kellyroach-optimizely** [comment]
SEE COMMENTS ADDED TO JIRA OASIS-2008

The P.R. #80 seems like a very promising start.  The ruby-sdk unit tests all pass.  I tried following the demo app's README.md and did make some headway, getting the demo app to launch into http://0.0.0.0:3000 in Google Chrome and going as far as populating the Configuration page with information from a personal Ruby SDK project.  However, at that point, I could not successfully go on.  Despite clicking "Save" a few times, attempting to move on via any of the other demo app buttons "Select Simulated Visitor", "Messages(Logs and Errors)", and "Shop" didn't function for me.  I would like to see these buttons work for me prior to approving the pull request.

Can you investigate and respond to the above?

**Comment by kellyroach-optimizely** [comment]
TEST
As mentioned in JIRA OASIS-2008, I think the demo app pages are basically
working for me now.  I have a few OTHER THOUGHTS in next comment.

**Comment by kellyroach-optimizely** [comment]
OTHER THOUGHTS:

The demo would be better if the "Select Simulated Visitor"
page would merely put a check mark or OW visibly leave selected
the visitor we select.  NOT jump to "Shop" page after we
tentatively select a visitor.  However, we can let this go.

"Shop" page.  The "Long Sleeve Shirt" looks like a red necklace,
not a long sleeve shirt.
Why is "Buy Now" button on the "Shop" page redirecting us
to the "Messages" page?  We don't think this is right for the
demo.  Stay on the "Shop" page!  Buy more.  Buy often.  Keep buying.
We do see the Messages page announce in a green bar
    "Successfully Purchased item Bo Henry for visitor Mike!"
However, we still disagree with leaving the "Shop" page
merely by pressing a "Buy Now" button.  This is less faithful
to the real use case scenario.

"Messages" page.  It seems like a nicely formatted <table>
of Optimizely's diagnostic messages.
* The "Search" field works.  (yay)
* The "Clear Messages" button works.

README.md
There will be at least 2 variation key's to make an interesting
A/B test demo, but the demo README.md will need to tell us at
least the non-default variation key we should enter in our own
Optimizely ruby-sdk experiment.  OW, we would have to read the
code carefully to discover this (only 151 files to check, but still
it is a pain to do).

QUESTION: How hard would it be to add a minimalist Checkout
page which simply presents an HTML <table> indicating the non-zero quantity
of each product purchased and a final <tr> announcing the total, and
I suppose a Clear button?  In code, current purchases are remembered
in a dictionary?

**Comment by rashidsp** [comment]
@kellyroach-optimizely all aforementioned suggestions implemented.
README.md yet to update.
Please review the changes.

**Comment by kellyroach-optimizely** [comment]
2 ERRORS RUNNING "rake test" IN THE "demo" SUBDIRECTORY

$ rake test
Run options: --seed 59483

# Running:

E

Error:
HomeControllerTest#test_should_get_index:
NameError: undefined local variable or method `home_index_url' for #<HomeControllerTest:0x007fbebb4ffac0>
    test/controllers/home_controller_test.rb:5:in `block in <class:HomeControllerTest>'

bin/rails test test/controllers/home_controller_test.rb:4

E

Error:
DemoControllerTest#test_should_get_new:
NameError: undefined local variable or method `demo_config_new_url' for #<DemoControllerTest:0x007fbec08199e0>
    test/controllers/demo_controller_test.rb:5:in `block in <class:DemoControllerTest>'

bin/rails test test/controllers/demo_controller_test.rb:4

**Comment by kellyroach-optimizely** [comment]
RE CHECKOUT PAGE UI

"Checkout" button should come before the Developer's "Messages" button.
"Checkout" page should show dollar amounts for purchases on each line .
The last row of "Checkout" table will include total dollar amount.

**Comment by kellyroach-optimizely** [comment]
RE DEMOING OPTIMIZELY A/B TESTING

I'm thinking the demo can have two experiments.

SHOP PAGE EXPERIMENT:

One experiment is very simple with 2 variations and affects the
visual presentation of the "Shop" page, but doesn't do more.

CHECKOUT PAGE EXPERIMENT:

The shopping site can allow for the possibility that the shopper
or variation hasn't elected for immediate Buy Now, but will commit
to purchasing on the Checkout page.

VARIATION A: The Shop "Buy Now" buttons do buy immediately and "Checkout"
page is just going to show a receipt.

VARIATION B: The Shop "Buy" buttons add tentative purchases to the
"Checkout" table.  In this variation, Checkout page "Clear checkout"
and "Buy Now" buttons are visible.

**Comment by mikeng13** [comment]
Going to close this for now as we re-design our demo apps.

**Pull request closed without merging**
