### PR TITLE
New Event Builder Payload + Numeric Event Support

### PR DESCRIPTION
**Pull request by oakbani**
✏️ New Payload
✏️ Numeric Event Support
✏️ Event Builder and Event Tags Unit Tests

### CODE REVIEW

**Comment by mikeng13** [comment]
build

**Comment by mikeng13** [comment]
build

**Comment by mikeng13** [comment]
build

**Comment by oakbani** [comment]
@mikeng13 Suggestions updated. Let me know if there is anything else

**Pull request merged**
