### PR TITLE
NotificationCenter should accept any Callable

### PR DESCRIPTION
**Pull request by jasonkarns**
## Summary

**The NotificationCenter learns to accept any callable object as the
  notification callback.**

It is uncommon in Ruby to require `Method` instances when any Callable
will suffice. Indeed, the idiomatic object for callbacks is a block.

With this change, the notification center can accept any callable, not
only `Method` instances; that is, any object that responds to `call`
(`Method`, lambdas, procs, or any object with a `.call` method)

If the callback parameter is omitted, a block may be provided instead.

## Issues

address item 3 of https://github.com/optimizely/ruby-sdk/issues/213

### CODE REVIEW

**Comment by jasonkarns** [comment]
Not sure what's going on with Travis. The failure is occurring before the test step even begins. https://travis-ci.org/optimizely/ruby-sdk/jobs/602833534

**Comment by jasonkarns** [comment]
> do you think it would be beneficial to provide a Proc.new {} test case as well (which also responds to :call)?

I can, but I don't think that additional test is valuable. We're already asserting that `Proc` instances can be provided (with the lambda test). It doesn't confirm anything that isn't already manifested in the tests and the `lambda` generation is more strict anyway (since the generated `Proc` checks arity).

Put another way, it's generally preferable to have only a single test fail for any given bug. Adding another test that fails for the same reason as an existing test doesn't provide value commensurate to its maintenance/carrying cost.

**Comment by msohailhussain** [comment]
@jasonkarns can you please review this PR and merge it in this branch. It has lint fixes that should be resolved first.
https://github.com/jasonkarns/optimizely-ruby/pull/1

**Comment by jasonkarns** [comment]
Merged! (feel free to make any future changes like that directly on the branch. I enabled "accept edits by maintainers" to facilitate this)

image

**Comment by msohailhussain** [comment]
@jasonkarns Thanks.

**Pull request merged**
